# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.19.2
_src_path: gh:oca/oca-addons-repo-template
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Module to help in agriculture management
repo_name: vertical-agriculture
repo_slug: vertical-agriculture
repo_website: https://github.com/OCA/vertical-agriculture
use_pyproject_toml: true
use_ruff: true

